### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by bilelmoussaoui** [fusion809/language-archlinux#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Arch Linux"
**Thrown From**: [language-archlinux](https://github.com/fusion809/language-archlinux) package, v0.2.4
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /home/bilal/.atom/packages/language-archlinux/lib/pkgbuild.coffee:10

TypeError: Cannot read property 'split' of undefined
    at module.exports.makepkg (/home/bilal/.atom/packages/language-archlinux/lib/pkgbuild.coffee:10:31)
    at atom-text-editor.atom.commands.add.pkgbuild:makepkg (/home/bilal/.atom/packages/language-archlinux/lib/index.coffee:6:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -6:11.5.0 command-palette:toggle (atom-text-editor.editor.power-mode.is-focused)
     -6:06.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:06.0 settings-view:install-packages-and-themes (atom-text-editor.editor.power-mode)
     -5:57 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 pkgbuild:makepkg (atom-text-editor.editor.power-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "terminal-plus",
      "vim-mode",
      "activate-power-mode"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-material-ui",
      "firewatch-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v1.2.13
auto-detect-indentation, v1.1.0
autocomplete-python, v1.7.5
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.13
firewatch-syntax, v1.0.1
flex-tool-bar, v0.10.0
gtk-dark-theme, v0.1.4
highlight-line, v0.11.1
highlight-selected, v0.11.2
language-archlinux, v0.2.4
language-arduino, v0.4.1
language-unix-shell, v0.29.3
linter, v1.11.5
minimap, v4.24.4
pigments, v0.29.2
python-autopep8, v0.1.3
python-isort, v0.0.7
tool-bar, v0.4.0
tool-bar-almighty, v0.6.1

# Dev
No dev packages
```

**Comment by fusion809** [comment]
This error doesn't occur for me, so I'm gonna have to rely on you to test if any attempted fixes work. Commit 26aa77f contains an attempted fix of this problem, to test it please run:

``` bash
apm remove language-archlinux
apm install https://github.com/fusion809/language-archlinux
```

open a new Atom window and run some Arch commands like namcap (<kbd>F8</kbd>) on an opened PKGBUILD.

**Comment by bilelmoussaoui** [comment]
I've an other issue now `: /bin/sh: ligne 0 : cd: /home/bilal/Dropbox/Projets/AUR: Aucun fichier ou dossier de ce type` the files are stored in `/home/bilal/Dropbox/Projets/AUR\ Packages/` but the extensions will only detect a part of the path.

**Comment by fusion809** [comment]
Ah, it'd help if I could get a purely English error message. Could ya start Atom from the command-line with:

``` bash
LANG="en_US.UTF-8" atom <FILEPATH>
```

where `<FILEPATH>` is to be replaced with whichever folder you'd like to start Atom in. Then copy whatever error message ya get.

**Comment by bilelmoussaoui** [comment]
`/bin/sh: line 0: cd: /home/bilal/Dropbox/Projets/AUR: No such file or directory`

**Comment by fusion809** [comment]
Sorry Bilal, I haven't a clue how to fix this error. It works fine for me. If you, or someone else, can come up with a pull request to fix this problem I will happily accept it.

**Comment by bilelmoussaoui** [comment]
Well, the issue is caused by this line i guess https://github.com/fusion809/language-archlinux/blob/master/lib/pkgbuild.coffee#L10. 
Is there a way to debug this by printnig the result of `filePath      = activeEditor.getPath()`?

**Comment by fusion809** [comment]
I just created a new branch ([fusion809-patch-1](https://github.com/fusion809/language-archlinux/tree/fusion809-patch-1)) that contains a possible way of debugging the issue. I hope it'll tell you the filePath and fileDirectory variables. To try it out, uninstall any existing `language-archlinux` installations and run:

``` bash
git clone https://github.com/fusion809/language-archlinux
cd language-archlinux
git checkout fusion809-patch-1
apm install
apm link .
```

**Comment by bilelmoussaoui** [comment]
`/bin/sh: line 0: cd: /home/bilal/Dropbox/Projets/AUR: No such file or directory 
filePath is /home/bilal/Dropbox/Projets/AUR Packages/gnome-twofactorauth/PKGBUILD; 
fileDirectory is /home/bilal/Dropbox/Projets/AUR Packages/gnome-twofactorauth`
I've found the issue. You will have to replace the empty space in the file path and the file directory with a "\ "

**Comment by fusion809** [comment]
Ah, well I just released v0.2.5, which should fix this problem (the method I use to replace whitespace with `\` is from http://stackoverflow.com/a/441035/1876983 for future reference). Please try it out.

**Comment by bilelmoussaoui** [comment]
One more issue with the latest version 
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Arch Linux"
**Thrown From**: [language-archlinux](https://github.com/fusion809/language-archlinux) package, v0.2.5

### Stack Trace

Failed to activate the language-archlinux package

```
At unexpected / in /home/bilal/.atom/packages/language-archlinux/lib/pkgbuild.coffee:28:45

SyntaxError: unexpected /
  at /home/bilal/.atom/packages/language-archlinux/lib/pkgbuild.coffee:28:45
```

### Commands

```
     -0:14.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 12x -0:11.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:03.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:02.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:01.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 pkgbuild:makepkg (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "terminal-plus",
      "vim-mode",
      "activate-power-mode"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-material-ui",
      "firewatch-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-ui, v1.2.13
auto-detect-indentation, v1.1.0
autocomplete-python, v1.7.5
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.14
firewatch-syntax, v1.0.1
flex-tool-bar, v0.10.0
gtk-dark-theme, v0.1.4
highlight-line, v0.11.1
highlight-selected, v0.11.2
language-archlinux, v0.2.5
language-arduino, v0.4.1
language-unix-shell, v0.29.3
linter, v1.11.6
minimap, v4.24.4
pigments, v0.29.2
python-autopep8, v0.1.3
python-isort, v0.0.7
tool-bar, v0.4.0
tool-bar-almighty, v0.6.1

# Dev
No dev packages
```

**Comment by fusion809** [comment]
I just got the same error, rofl. I just published another attempted fix (v0.2.6).

**Comment by bilelmoussaoui** [comment]
The replace code does not work :/

**Comment by fusion809** [comment]
You wouldn't happen to have any ideas as to how to do this would ya? 'cause CoffeeScript/JS aren't my strong-suits. Only solution I have left to try is to run `.split(' ').join('\ ')` on `fileDirectory`. These patches will be becoming disruptive to other users of this package so I'm gonna try these fixes in that fusion809-patch-1 branch.

**Comment by bilelmoussaoui** [comment]
I will give it a try

**Comment by fusion809** [comment]
Just implemented this fix on fusion809-patch-1. So running:

``` bash
git clone https://github.com/fusion809/language-archlinux
cd language-archlinux
git checkout fusion809-patch-1
apm install
apm link .
```

should install it for ya to try the attempted fix.

**Comment by bilelmoussaoui** [comment]
Pushed a PR to fix this

**Comment by bilelmoussaoui** [comment]
@fusion809 Would you love creating an other package for Solus packaging ? https://wiki.solus-project.com/Package.yml

**Comment by fusion809** [comment]
Well I don't use Solus, the distros I use on a regular basis are Arch Linux, Gentoo Linux, Sabayon Linux and Ubuntu. With Arch taking up >90% of my usage share. Well, I'll attempt to create a `language-solus` package. As I don't use that distro that it'd be prudent for ya and anyone else interested in using it to test it out thoroughly for me and file any necessary bug reports.

**Comment by bilelmoussaoui** [comment]
@fusion809 I don't use Solus neither; i think the community of Solus will love the package :+1:

**Comment by fusion809** [comment]
@bil-elmoussaoui I created the package and I just announced it on their forums. https://solus-project.com/forums/viewtopic.php?f=14&t=1507&p=8241#p8241
