### ISSUE TITLE
Improvement suggestion: adding newpkg command

### ISSUE THREAD

**Issue by fusion809** [fusion809/language-archlinux#11]
Hi, @bil-elmoussaoui 

**NOTE**: Not sure what your schedule is like, so I should probably mention I will open a new thread requesting help with respect to this issue at discuss.atom.io, in case someone else has a solution. 

I think a nice new feature for this package, that I think you will be better equipped to implement than I (I really don't know how to do this, mostly because of the fact it requires user input, I have looked at some packages that do this trying to find bits of code I need to copy but I must admit I'm confused as to what is relevant to this new feature and what is not) is a `newpkg` command. This command would open a dialog window, taking an input and running:

```
git clone ssh+git://aur@aur.archlinux.org/#{name}.git #{fileDirectory}/#{name}
```

where `#{name}` is the input taken from the dialog window and `#{fileDirectory}` is the directory of the currently-opened file. If someone else is reading this that has an idea of how to implement this feel free to open a pull request or instruct me how to do this. I will be more than willing to accept any pulls. 

Thanks for your time,
Brenton

**Comment by bilelmoussaoui** [comment]
I will try to do it as soon as possible, can you assign me to it so i won't forget ?😃

**Comment by fusion809** [comment]
To do this I need to add you as a collaborator. So I just sent ya an invitation.

**Comment by bilelmoussaoui** [comment]
Done

**Comment by fusion809** [comment]
It is finished! The reply I got from @DamnedScholar was so great that I was able to do this myself https://discuss.atom.io/t/how-can-i-prompt-a-user-for-input-and-use-this-as-a-variable-in-my-package/30342.
