### ISSUE TITLE
Failed to load the language-archlinux package

### ISSUE THREAD

**Issue by tensor5** [fusion809/language-archlinux#13]
I encounter this error when I load Atom after the last upgrade of language-archlinux.

**Atom Version**: 1.8.0
**System**: linux 4.6.4-1-ck
**Thrown From**: [language-archlinux](https://github.com/fusion809/language-archlinux) package, v0.8.2
### Stack Trace

Failed to load the language-archlinux package

```
At 'styles.less' wasn't found in /home/nicola/.atom/packages/language-archlinux/styles/pkgInputView.less:1:0

LessError: 'styles.less' wasn't found
  at /home/nicola/.atom/packages/language-archlinux/styles/pkgInputView.less:1:0
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "linter-eslint"
    ],
    "projectHome": "/home/nicola/projects",
    "themes": [
      "adwaita-pro-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
adwaita-pro-ui, v2.1.4
atom-notifier, v0.5.1
file-icons, v1.7.17
haskell-unicode-snippets, v0.1.1
javascript-snippets, v1.2.1
linter, v1.11.14
linter-markdown, v1.5.2

# Dev
No dev packages
```

**Comment by fusion809** [comment]
I just pushed a commit to fix this. Could ya try it out? You can try it out by removing language-archlinux and re-installing it with:

``` bash
apm install fusion809/language-archlinux
```

**Comment by tensor5** [comment]
Fix works. Thanks!
