### ISSUE TITLE
namcap does not work

### ISSUE THREAD

**Issue by bilelmoussaoui** [fusion809/language-archlinux#4]
Using `namcap` does not work and i don't have any error message
![screenshot from 2016-06-10 16-36-39](https://cloud.githubusercontent.com/assets/7660997/15967843/a150dbc4-2f29-11e6-9f34-30ee6a8efbbd.png)

**Comment by fusion809** [comment]
I don't mean to offend ya or anything but it worked before your pulls earlier today... So I suspect it's something in one of your pulls, so I'll see what's the problem.

**Comment by bilelmoussaoui** [comment]
reverting my commit didn't fix that btw...

**Comment by fusion809** [comment]
Ah, sorry. I used namcap a few days or so ago using this package and it was fine. I can't think of any changes I made that could have caused this... Any ideas?

**Comment by bilelmoussaoui** [comment]
If you can add an other debug to show the executed command with the path file so we can check if everything is fine? 
And for makepkg, the file is created successfully but i don't get any success message :/

**Comment by fusion809** [comment]
I found the problem... L15-L20 of the package.json listed all commands, except namcap. I also added debugging features though, so if it fails it will tell you the exact command ran.

**Comment by bilelmoussaoui** [comment]
Thanks for the quick fix 

```
command is: namcap /home/bilal/Dropbox/Projets/AUR Packages/gnome-twofactorauth/PKGBUILD
```

but this still wont work until you revert back my commit :P 
The makepkg now shows a success message! :dancer:

**Comment by fusion809** [comment]
Revert back you mean replace `filePath = activeEditor.getPath()` with `filePath = activeEditor.getPath().split(" ").join("\\ ")`?

**Comment by bilelmoussaoui** [comment]
Yeah, and there's no need to repeat the same code for filePath, fileDirectory for each command:) tested your commit with the old `pkgbuild.coffee` and everything works fine

**Comment by fusion809** [comment]
Done in v0.2.17. So I'm closing this issue.
