### ISSUE TITLE
show a spinner during the makepkg

### ISSUE THREAD

**Issue by bilelmoussaoui** [fusion809/language-archlinux#7]
Once i ran a `makepkg`, there's no interaction with the user and you might think that something is not going on. 
I think the best idea is to show a spinner like what `atom-beautify` do during the build

**Comment by fusion809** [comment]
OK, if you'd like to implement it go ahead. I don't know how to though, but I'll gladly accept any pulls.

**Comment by bilelmoussaoui** [comment]
I might do that later but it's quite easy. Atom-beautify uses this object https://github.com/Glavin001/atom-beautify/blob/master/src/views/loading-view.coffee which shows a spinner view. 
And before running makepkg you show the spinner with something like this https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L58
and once everything ends you hide it
